- name: Fetch Issues
  run: |
    echo "Fetching issues from GitHub API..."
    
    curl -s -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
         "https://api.github.com/repos/${{ github.repository }}/issues" > issues_raw.json

    echo "Raw API response:"
    cat issues_raw.json

    if grep -q '"message":' issues_raw.json; then
      echo "Error in API response!"
      cat issues_raw.json
      exit 1
    fi

    if ! jq empty issues_raw.json; then
      echo "Invalid JSON response!"
      exit 1
    fi

    jq '[.[] | select(.pull_request | not) | {title: .title, url: .html_url, created_at: .created_at}]' issues_raw.json > status.json

    echo "Processed status.json:"
    cat status.json
