name: Status Dashboard Update

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12 PM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Open Issues from GitHub API
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/issues?state=open" \
               | jq '.' > status.json

      - name: Commit and Push Status File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase  # Pull the latest changes before committing
          git add status.json
          git diff --staged --quiet || git commit -m "Updated status dashboard"
          git stash  # Stash any unstaged changes
          git pull origin main --rebase  # Pull latest changes without conflict
          git stash pop || echo "No stashed changes to apply"
          git push https://x-access-token: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@github.com/SeemaaKohlii/status-dashboard.git
          git push
