name: Update Status Dashboard

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Open Issues
        run: |
          echo "Fetching open issues..."
          curl -s -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ secrets.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 }}" \
               "https://api.github.com/repos/${{ github.repository }}/issues?state=open" \
               | jq '[.[] | {title: .title, url: .html_url, created_at: .created_at}]' > status.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          git add status.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Updated issue list"
            git push https://x-access-token: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@github.com/SeemaaKohlii/status-dashboard.git
          fi
