name: Update Status Dashboard

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Open and Closed Issues
        run: |
          echo "Fetching open and closed issues from GitHub API..."

          # Get Open Issues
          curl -s -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/issues?state=open" > open_issues.json
          
          # Get Closed Issues
          curl -s -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/issues?state=closed" > closed_issues.json

          echo "Fetched issues. Checking JSON validity..."

          # Debug raw JSON responses
          echo "
